### ISSUE TITLE
RDFDataMgr.read(markLogicDatasetGraph, "file.nt" Lang.NTRIPLES ) inserts two sets of triples into ML DB

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-jena#1]
Originally submitted by @kkanthet 

When we read triples into MarklogicDataset , there are two sets of tripeles/quads inserted into DB and also is noticeably slow for a file with one triple in it.

MarkLogicDatasetGraph markLogicDatasetGraph = MarkLogicDatasetGraphFactory.createDatasetGraph(writerClient);
RDFDataMgr.read(markLogicDatasetGraphWriter, "/testData/file.nt", Lang.NTRIPLES );

where file.nt has ::
<#electricVehicle2> http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://people.aifb.kit.edu/awa/2011/smartgrid/schema/smartgrid#ElectricVehicle .

**Comment by grechaw** [comment]
Good catch -- this is fixed.

**Comment by kkanthet** [comment]
Verified that no duplicates are inserted .
