### ISSUE TITLE
Throw UnSupported Exception instead of returning -1 or empty 

### ISSUE THREAD

**Issue by kkanthet** [marklogic/marklogic-jena#11]
Throw unsupported Exception for functionality not supported by  MarkLogic dataset graph

Ex: get size(), lock(), getContext

**Comment by grechaw** [comment]
Actually I found there's a Lock implementation called LockNone that is appropriate for getLock(), and the overridden getContext() is OK.  gize() is throwing an exception now.  I'll get these changes ready for a PR.

**Comment by grechaw** [comment]
This change is pushed to develop
