### ISSUE TITLE
 update java api client dep in gradle

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-jena#14]
As part of release process (coordinating with @kkanthet ) we need to update gradle to point to maven central deployed java client api 3.0.4.

**Comment by grechaw** [comment]
I've updated rc-1.0.0 to have version 1.0.0.  (that's a little different from 1.0.1-- I'm hoping that's all right.)

**Comment by grechaw** [comment]
The Java Client API dependency was not updated for the 1.0.1 release, unfortunately.  I'm reopening this task to do that for 1.0.2

**Comment by kkanthet** [comment]
@grechaw we did update java-client-api dependency to point to 3.0.5 in master branch and release tag https://github.com/marklogic/marklogic-jena/blob/1.0.1/marklogic-jena/build.gradle#L28 . What am i missing ..?

**Comment by grechaw** [comment]
no we did not.
We missed it because we cannot actually verify this change until after java client api is released to maven central.  
I've made the change now, about to push to develop.  If possible, I think it would be best to cut 1.0.2 with this change, as 1.0.1 really does not take advantage of bugfixes in the java layer.

**Comment by grechaw** [comment]
So for what its worth, marklogic-jena appears ready for release now
