### ISSUE TITLE
Timer for microbatch of add() is never cancelled.

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-jena#17]
When you start an application with marklogic-jena, there's a timer task to ensure triples added wit add() are periodically flushed and sent to the server.
This timer task should be cancelled in some final block.  It can block an application stopping now.

**Comment by grechaw** [comment]
I actually have the fix ready for this.  when you close() a connection, the timer is cancelled.

**Comment by grechaw** [comment]
I was able to verify this fix by running examples, and comparing behavior with and without close().

If you don't close(), then the timer task may prevent the main loop from exiting.

**Comment by kkanthet** [comment]
Verified the timer thread is closed when dataset is closed.
