### ISSUE TITLE
scheduleFixedRate

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-jena#20]
have you considered using Date() to init timer aka

```
timer.scheduleAtFixedRate(cache, new Date(), 1000);
```

vs

```
timer.scheduleAtFixedRate(cache, 1000, 1000);
```

**Comment by xquery** [comment]
ignore this, I was looking into overloaded variant and tests now confirm orig approach is good

**Comment by grechaw** [comment]
ah ok :)
