### ISSUE TITLE
Bad Default Base URI for CRUD

### ISSUE THREAD

**Issue by kkanthet** [marklogic/marklogic-jena#24]
There is a default base uri set for Query, but no default set on CRUD.
more details on issue #23

**Comment by grechaw** [comment]
I've just dug this issue up and it looks like Jena 3 may have changed behavior...

No, verified that Jena 2 also seems no longer to add unexpected BASE.

I'll close this as N/A.  Before, I wasn't sure how to fix, and now I don't think a fix is needed.
