### ISSUE TITLE
add Model based example

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-jena#28]
https://github.com/marklogic/marklogic-jena/tree/master/marklogic-jena-examples/src/main/java/com/marklogic/jena/examples

add new example using jena model abstraction eg. DataSet, Model, Statement, Resource and Literal

**Comment by grechaw** [comment]
I put this example together just now.

**Comment by grechaw** [comment]
OK To ship/close this issue @kkanthet  ?
