### ISSUE TITLE
Upgrade to jena 3.1.0

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-jena#40]
3.1.0 has bugfixes and cleanup that we should get into the develop branch to stay current for the next release.

**Comment by grechaw** [comment]
I've tested this upgrade already - it was near trivial to get in place, and I'll make a PR for it after 7/22

**Comment by sashamitrovich** [comment]
@grechaw, when can we expect this to be released, a prospect has a use case with 3.1.0 and wants to use it?

**Comment by grechaw** [comment]
Hi @sashamitrovich  I can't give you release dates, but I plan to do merge this dependency into develop branch within the next week.  I will consult with our product managers about releasing- there's nothing technically to prevent such a thing.

**Comment by sashamitrovich** [comment]
Thanks, @grechaw! Would it help if we mention to @sbuxton that a prospect is waiting on this?
