### ISSUE TITLE
 update copyright 2017

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-jena#54]
Update all copyright notices in marklogic-jena to 2017

**Comment by grechaw** [comment]
This is complete, in PR

**Comment by kkanthet** [comment]
@grechaw  files in https://github.com/marklogic/marklogic-jena/tree/develop/marklogic-jena/src/main/java/com/marklogic/semantics/jena/engine 
are not updated with Copyright.

**Comment by grechaw** [comment]
I'll add that change to the PR that's currently outstanding.

**Comment by grechaw** [comment]
OK, Added to PR #60 .  Not sure why I missed those previously, a good catch.
