### ISSUE TITLE
Request to have the sync timer values settable for tuning purposes

### ISSUE THREAD

**Issue by JohnJ9ml** [marklogic/marklogic-jena#55]
It would be helpful for the sync timer frequency for pushing adds and deletes down to the ML database to be exposed and settable from the JenaDatabaseClient. This would be helpful for the purposes of tuning the behavior and optimizing based upon individual application usage patterns. This would also aid in eliminating or identifying the sync behavior as a possible cause of performance issues within a client application.

**Comment by grechaw** [comment]
Hi @JohnJ9ml , in reviewing how Timer works, I'm thinking I should have not used the fixed rate anyway.
I'm going to propose we move to fixed delay timing, which might help in keeping processes from stomping on each other.

**Comment by grechaw** [comment]
This is in PR -- I simply added a getter and setter in JenaDatabaseClient.

**Comment by grechaw** [comment]
It occurs to me you might want it in a properties file though.  Is that the case @JohnJ9ml ?

**Comment by kkanthet** [comment]
No regressions , hence shipping
