### ISSUE TITLE
upgrade dependencies

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-jena#67]
as part of next release, upgrade java client to 4.0.3, along with other dependencies as appropriate.

**Comment by grechaw** [comment]
Assiging to our illustrious QA folks -- all dependencies have been upgraded.

Ideally the functional tests would get some updates too -- I would rather they use sfl4j and ml-gradle for deployment, would speed them up some.

**Comment by kkanthet** [comment]
Will have to create a different task and prioritize it to move functional test to mlGradle instead of REST API setups. 
All functional tests and unit tests pass against 9.0-4-nightly and develop with marklogic-client-4.0.3
