### ISSUE TITLE
upgrade Jena and MarkLogic dependencies

### ISSUE THREAD

**Issue by ehennum** [marklogic/marklogic-jena#76]
latest stable production releases

**Comment by AlexTo** [comment]
hi @ehennum, do you have any build issues after upgrading the dependencies?

**Comment by ehennum** [comment]
@AlexTo , the MarkLogic Java API dependency was a clean update, but the Jena upgrade had an issue.

The Jena Transactional interface added some methods.  marklogic-jena has an implementation of that interface, so the marklogic-jena class implementing Transactional must add some methods.

I need to study up on the Jena transactional model before writing those methods.

**Comment by AlexTo** [comment]
I thought so too as the last time I attempted to upgrade Jena to 3.7.0 and realised I needed to also update MarkLogic classes accordingly. Eventually I removed support for Jena in our software as I didn't have the time to do so but this update is highly desired :) hopefully MarkLogic team could provide an upgrade soon

**Comment by ehennum** [comment]
Although the new Transactional methods seem biased toward a specific transactional model, the impacts on marklogic-jena seem straightforward, in that the MarkLogic Java API only supports write transactions for multistatement transactions.

Anyway, the unit tests ran fine after the version upgrade. No new functional tests are needed because the version upgrade doesn't add any new functionality.  

If the version upgrade doesn't cause any regressions on the internal Jenkins job that runs the functional tests, I expect it is good as a release candidate.

**Comment by georgeajit** [comment]
Closing this issue.

**Comment by AlexTo** [comment]
Hi just checking if there is any plan to release this upgrade yet to support Jena 3.1x.0 ?
Thank you

**Comment by ehennum** [comment]
@AlexTo , the marklogic-jena project is now a community project:

https://github.com/marklogic/marklogic-jena/blob/master/LICENSE#L10

Contrary to our expectations, the project hasn't seen much interest:

https://github.com/marklogic/marklogic-jena/graphs/traffic

**Comment by AlexTo** [comment]
I pulled the "Dev" branch which has your latest commit and it seems to work ok with Jena 3.12.0
Thanks

**Comment by fp-smartlogic** [comment]
Hi. Are there any plans of upgrading Jena dependency to 4.x version?

**Comment by rjrudin** [comment]
This will be addressed in the next release. Thanks to @fp-smartlogic  for doing the work of supporting Jena 4.x.
